apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hac-dev-ipun
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hac-dev-ipun
    app.kubernetes.io/part-of: hac-dev-1
  name: hac-dev-ipun
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: hac-dev-ipun
status:
  loadBalancer: {}
